# Copyright 2012-2016 splinter authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

sudo: required
services:
  - xvfb
before_install:
  - export DISPLAY=:99.0
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - ./travis-install.bash
language: python
addons:
  chrome: stable
  firefox: latest
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DRIVER='-n 6 tests/test_webdriver_remote.py tests/test_flaskclient.py tests/test_browser.py tests/test_element_list.py tests/test_request_handler.py tests/test_djangoclient.py tests/test_zopetestbrowser.py'
  - DRIVER='-n 6 tests/test_webdriver.py tests/test_webdriver_firefox.py tests/test_webdriver_chrome.py'
install:
  - export PATH=$HOME:$PATH
script:
  - pip install tox
  - tox -- ${DRIVER}
dist: xenial
